### PR TITLE
watchmyback

### PR DESCRIPTION
**Pull request by john-swana**

### CODE REVIEW

**Comment by end3r** [comment]
Hey, thanks for using the bot. Have you attached the zip to the release? Also, seems the manifest is missing.

**Comment by end3r** [comment]
@swashvirus do you need any help passing the checks?

**Comment by john-swana** [comment]
yup

**Comment by john-swana** [comment]
help

**Comment by Platane** [comment]
Hi, it seems that you have a game.zip file commited, the bot will look for this file in the release.

You will need to create a new release (no need to open a new pull request) and add the game.zip file as release asset. Which is well explained in this guide : https://help.github.com/en/articles/creating-releases

Then you want to add a manifest.json file, which should look like this: https://github.com/js13kGames/entry/blob/master/manifest.json

**Comment by Platane** [comment]
oh and then it will ask you to add images, everything is explained here : https://github.com/js13kGames/bot/blob/master/doc/how-to-submit.md#pull-request

**Pull request closed without merging**
